#pragma config(Sensor, dgtl1,  ultrasonic1,    sensorSONAR_cm)
#pragma config(Sensor, dgtl5,  bumper1,        sensorTouch)
#pragma config(Motor,  port1,           leftMotor,     tmotorVex393_HBridge, openLoop)
#pragma config(Motor,  port2,           rightMotor,    tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port3,           catapult,      tmotorVex393_MC29, openLoop)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

task main()
{
	while(SensorValue(ultrasonic1) > 10  || SensorValue(ultrasonic1) == -1){
		startMotor(port1, -25);
		startMotor(port2, -25);
	}
	stop();
  startMotor(port3, 80);
	wait(1);
	stop();

	while(SensorValue(bumper1)==0){
		startMotor(port1, 25);
		startMotor(port2, 25);
		if(SensorValue(bumper1)== 1){
    	stopMotor(port1);
    	stopMotor(port2);
 		}
	}

}
